version: '3.4'

services:
  auth-db:
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: AuthPa$$1    # Note that $ needs to be escaped as $$ - so pass is actually AuthPa$1
      MSSQL_PID: Developer
    ports:
      - 1401:1433
    volumes:
      - sqlserver:/var/opt/mssql

  email:
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - overlay

  auth:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - 44396:443
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  auth-admin:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - 44344:443
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
