version: '3.4'

services:
  auth-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    networks:
      - overlay

  auth:
    image: ${DOCKER_REGISTRY-}auth
    build:
      context: .
      dockerfile: src/Auth/Dockerfile
    networks:
      - overlay

  auth-admin:
    image: ${DOCKER_REGISTRY-}auth-admin
    build:
      context: .
      dockerfile: src/Auth.Admin/Dockerfile
    networks:
      - overlay

volumes:
  sqlserver:
    driver: local

networks:
  overlay:
